[build]
  command = "npm start"
  publish = "public"
  Functions = "functions"
[build.processing]
  skip_processing = true
[build.processing.js]
  bundle = true
  minify = true
[[plugins]]
  package = "@netlify/plugin-emails"
[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "https://cedemi.netlify.app"
  to = "https://www.cedemi.fr"
  status = 301
  force = true