[build]
  command = "npm start"
  publish = "public"
  Functions = "functions"
[build.processing]
  skip_processing = false
[build.processing.js]
  bundle = true
  minify = true
[[plugins]]
  package = "@netlify/plugin-emails"