[build]
  command = "npm start"
  publish = "public"
  Functions = "functions"
[[plugins]]
  package = "@netlify/plugin-emails"
[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "https://cedemi.netlify.app"
  to = "https://www.cedemi.fr"
  status = 301
  force = true
[[redirects]]
  from = "https://cedemi.netlify.app/fr_en"
  to = "https://www.cedemi.fr/fr_en"
  status = 301
  force = true